version: "3.8"

services:
  pg_redash:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redash
    volumes:
      - ./db/pg_redash:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pg_data:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redash:
    image: redash/redash:latest
    depends_on:
      - pg_redash
      - redis
    environment:
      REDASH_DATABASE_URL: "postgresql://useradmin:password@pg_redash:5432/redash"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      PYTHONUNBUFFERED: 0
    ports:
      - "5004:5000"
    command: server

  redash_worker:
    image: redash/redash:latest
    depends_on:
      - pg_redash
      - redis
    environment:
      REDASH_DATABASE_URL: "postgresql://useradmin:password@pg_redash:5432/redash"
      REDASH_REDIS_URL: "redis://redis:6379/0"
    command: worker

  redis:
    image: redis:7
    restart: always
